### ISSUE TITLE
CREATE TABLE indentation

### ISSUE THREAD

**Issue by felipeochoa** [bsvingen/sql-indent#6]
This is how it indents right now (`sql-indent-offset` is set to 4)
```sql
CREATE TABLE users {
        name TEXT
        }
```

It would be great to:

1. Only indent the fields by one level
2. Have the closing brace at column 0

**1** looks like an easy fix in `sql-indent-level-delta`, but it seems as though the double indent is actually working as intended. Is this behavior intentional? If so, it would be great to make it configurable.

**2** I think is just a matter of subtracting 1 from the indent delta when `(looking-at "[]})]")`

Let me know what you think on point `1` and I'll submit a PR with both fixes

**Comment by sondr3** [comment]
Hello, I've created a small fork of this library to include some of the pull requests that haven't been merged yet. I was wondering if you still had the patch available? I've tried to make it behave like you want it to do here, but I don't have enough experience with Elisp to be able to fix it.

**Comment by braham-snyder** [comment]
looks like you've already ran into https://github.com/alex-hhh/emacs-sql-indent yourself, but for posterity: that linked package is more actively maintained than this one at the moment (and, e.g., already indents the fields by only one level)

**Comment by sondr3** [comment]
Yep, ran into it by accident when trying to find this repo again when searching on GitHub :smiley:
